### ISSUE TITLE
TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by Koolstr** [gyorgygutai/react-material-ripple#1]
I get the following error no matter where I try to use your component, or no matter what children are contained within the component:

```
TypeError: Cannot read property 'element' of undefined
./node_modules/react-material-ripple/dist/Ripple.js:124

  121 | }(_react2.default.Component);
  122 | 
  123 | Ripple.propTypes = {
> 124 |   children: _react2.default.PropTypes.element,
  125 |   className: _react2.default.PropTypes.string
  126 | };
  127 |
```
What is going on here? Does this module support the latest versions of React?

**Comment by gyorgygutai** [comment]
Fixed. Thank you!

**Comment by Koolstr** [comment]
Took long enough, but I'm glad it was at least eventually resolved.

**Comment by gyorgygutai** [comment]
Honestly, I just missed the notifications for this repo. Sorry for that.
